---
- hosts: web
  vars:
   dockerport: 8888
   contport: 8080
  become: true
  tasks:
  - name: Update apt repo
    apt: update_cache=yes name=docker.io state=present
  - name: Remove Existing Docker Container 
    shell:
     cmd: docker rm --force hellostaragile || echo
  - name: Remove Existing Docker Image
    shell:
     cmd: docker rmi --force kerurpm/hellowithwar
  - name: Start Docker Container
    shell:
     cmd: docker run -d --name=hellostaragile -p {{ dockerport }}:{{ contport }} kerurpm/hellowithwar
